# Generated by Django 4.1.2 on 2022-10-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='less_images',
            field=models.FileField(blank=True, upload_to='static/images/lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='less_notes',
            field=models.FileField(blank=True, upload_to='static/lesson/notes/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='less_video',
            field=models.FileField(blank=True, upload_to='static/lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_img',
            field=models.FileField(blank=True, upload_to='static/images/programs/'),
        ),
    ]
